apiVersion: batch/v1
kind: Job
metadata:
  name: heart-model-training
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: mlops-trainer
      restartPolicy: Never
      containers:
      - name: trainer
        image: us-central1-docker.pkg.dev/mlops-final-001/mlops-repo/heart-trainer:latest
        command: ["python", "src/train.py"]
        args:
          - "--model-dir=gs://mlops-final-001-mlops-artifacts/latest"
